# render.yaml
services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your_secret_key"
      - key: ALLOWED_HOSTS
        value: "your-app.onrender.com"
