# Generated by Django 5.1.4 on 2024-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('MOP', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
